#!/bin/bash

echo "🚀 RazorFlow AI v2.0 - Deployment Script"
echo "========================================"

# Check if we're in the right directory
if [ ! -f "README.md" ] || [ ! -d "frontend" ] || [ ! -d "backend" ]; then
    echo "❌ Error: Run this script from the RazorFlow-AI-v2 root directory"
    exit 1
fi

echo ""
echo "📋 Pre-deployment checklist:"
echo "✅ Clean project structure created"
echo "✅ Frontend React app ready"
echo "✅ Backend FastAPI ready"
echo "✅ GitHub Actions configured"
echo "✅ Railway configuration ready"

echo ""
echo "🔧 Next steps for deployment:"
echo ""
echo "1. 📱 Create GitHub Repository:"
echo "   - Go to https://github.com/new"
echo "   - Repository name: RazorFlow-AI-v2"
echo "   - Description: Business Automation Platform with AI Assistants"
echo "   - Public repository"
echo ""
echo "2. 🔗 Connect Repository:"
echo "   git remote add origin https://github.com/razor303jc/RazorFlow-AI-v2.git"
echo "   git push -u origin main"
echo ""
echo "3. 🌐 Deploy Frontend (GitHub Pages):"
echo "   - GitHub will auto-deploy via Actions"
echo "   - Enable GitHub Pages in repository settings"
echo "   - Live at: https://razor303jc.github.io/RazorFlow-AI-v2/"
echo ""
echo "4. 🚂 Deploy Backend (Railway):"
echo "   - Go to https://railway.app/new"
echo "   - Connect GitHub repository"
echo "   - Railway auto-detects railway.json config"
echo "   - Live API endpoint provided"
echo ""
echo "5. 🔧 Update Frontend API URL:"
echo "   - Update API_BASE in frontend/src/App.jsx"
echo "   - Replace with your Railway URL"
echo "   - Commit and push changes"
echo ""
echo "💰 Estimated Monthly Costs:"
echo "   - GitHub Pages: $0 (Free)"
echo "   - Railway: $0-20 (Free tier + optional Pro)"
echo "   - Total: $0-20/month"
echo ""
echo "🎯 Revenue Potential:"
echo "   - Starter Plan: $99/month"
echo "   - Professional: $299/month" 
echo "   - Enterprise: $799/month"
echo ""
echo "Ready to launch your AI business platform! 🚀"
